services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant_data:/qdrant/storage
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - qdrant
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

configs:
  qdrant_config:
    content: |
      log_level: INFO
